# Generated by Django 3.2.25 on 2024-12-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الكوبون')),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=20, null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ بدأ الخصم')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ انتهاء الخصم')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'كوبونات الخصم',
                'verbose_name_plural': 'كوبونات الخصم',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المتوفرة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=20, null=True, verbose_name='نوع الخصم ان وجد')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة الخصم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'المنتجات',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اقسام المنتجات',
                'verbose_name_plural': 'اقسام المنتجات',
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القسم الفرعي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف اقسم الفرعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='api.section')),
            ],
            options={
                'verbose_name': 'الاقسام الفرعية للمنتج',
                'verbose_name_plural': 'الاقسام الفرعية للمنتج',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
            options={
                'verbose_name': 'صور المنتج',
                'verbose_name_plural': 'صور المنتج',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.subsection'),
        ),
    ]
