# Generated by Django 3.2.25 on 2024-12-12 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20241212_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'السلة', 'verbose_name_plural': 'السلة'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'طلبات السلة (هنا يمكنك معرفة المنتجات التي اضافها المستخدم الى سلته لكنه لم يكمل طلبه)', 'verbose_name_plural': 'طلبات السلة (هنا يمكنك معرفة المنتجات التي اضافها المستخدم الى سلته لكنه لم يكمل طلبه)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'الطلبات ', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'المنتجات المطلوبة', 'verbose_name_plural': 'المنتجات المطلوبة'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_images/', verbose_name='صورة الشعار'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='api.section', verbose_name='اسم القسم '),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='api.subsection', verbose_name='اسم القسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coupon', verbose_name='الكوبون المطبق اذا كان هنالك'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='الرمز الفريد للسلة'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='المنتجات'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('ثابت', 'ثابت'), ('نسبة مئوية', 'نسبة مئوية')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='هل تريد تفعيل رمز الخصم؟'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='api.subsection', verbose_name='اسم القسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='government',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محافظة السكن'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='هل تم تأكيد رقم الهاتف؟'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer', verbose_name='الطلبات'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.product', verbose_name='المنتجات المطلوبة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية االمطلوبة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الكلي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('ثابت', 'ثابت'), ('نسبة مئوية', 'نسبة مئوية')], max_length=20, null=True, verbose_name='نوع الخصم ان وجد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.subsection', verbose_name='اسم اقسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف القسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='api.section', verbose_name='اسم القسم'),
        ),
    ]
