# Generated by Django 5.1.4 on 2024-12-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alert_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم البراند')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة البراند')),
            ],
            options={
                'verbose_name': 'البراند',
                'verbose_name_plural': 'البراند',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='api.brand', verbose_name='الى اي براند ينمتي المنتج'),
        ),
    ]
