# Generated by Django 5.1.4 on 2024-12-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title', 'description'], name='api_product_title_461769_idx'),
        ),
    ]
