# Generated by Django 5.1.4 on 2024-12-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='', help_text='Platform of the device (iOS or Android)', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
