# Generated by Django 5.1.4 on 2024-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_devicetoken_created_at_devicetoken_platform_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_name'], name='api_brand_brand_n_c97533_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='api_coupon_code_f609b1_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['subsection'], name='api_coupon_subsect_a04025_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date'], name='api_coupon_start_d_4e5fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['end_date'], name='api_coupon_end_dat_4daaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='api_custome_phone_n_f7efe2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='api_orderit_order_i_3f9c70_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='api_orderit_product_1a13b6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_section'], name='api_product_sub_sec_1987e9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='api_product_price_b6b1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='subsection',
            index=models.Index(fields=['section'], name='api_subsect_section_143dbb_idx'),
        ),
    ]
