# Generated by Django 5.1.4 on 2025-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_brand_api_brand_brand_n_c97533_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favoured',
            field=models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], default='لا', max_length=3, verbose_name='هل تريد اظهار المنتج على الصفحة الرئيسية ؟'),
        ),
    ]
