# Generated by Django 5.1.4 on 2025-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_is_favoured'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subsection_images/', verbose_name='صورة القسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brandImage/', verbose_name='صورة البراند'),
        ),
    ]
