# Generated by Django 5.1.4 on 2025-01-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subsection_image_alter_brand_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/', verbose_name='صورة القسم الفرعي'),
        ),
    ]
