# Generated by Django 5.1.4 on 2025-02-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_section_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'كوبون الخصم', 'verbose_name_plural': 'كوبونات الخصم'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' المنتجات', 'verbose_name_plural': 'المنتجات '},
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='api_coupon_subsect_a04025_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_title_461769_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_sub_sec_1987e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_price_b6b1d7_idx',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='subsection',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.coupon', verbose_name='الكوبون المستخدم'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('discount_type', 'ثابت'), ('discount_value__gte', 0), ('discount_value__lte', models.F('price'))), models.Q(('discount_type', 'نسبة مئوية'), ('discount_value__range', (0, 100))), ('discount_type__isnull', True), _connector='OR')), name='valid_discount'),
        ),
    ]
